### ISSUE TITLE
Doublon dans les transitions

### ISSUE THREAD

**Issue by El0o** [El0o/Finite_Automata_Project#1]
Après standardisation, il arrive que certaines transitions soient dédoublée :

![image](https://github.com/El0o/Finite_Automata_Project/assets/125570987/feda9bbf-bbf4-49fc-b79d-9a2226e0430c)

Le problème doit sûrement venir de la fonction standardization() elle même.

**Comment by El0o** [comment]
Autre exemple :
![image](https://github.com/El0o/Finite_Automata_Project/assets/125570987/326c0e96-0012-4da1-9955-722f70907e5e)

**Comment by EnoraLaz** [comment]
close
